

server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thiagodemeterko/spring-cloud-challenge-config-repo
          search-paths: distancia,monolito,pagamento